parameters:
#    curso_main.example.class: Curso\MainBundle\Example

services:
#    curso_main.example:
#        class: %curso_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
