<?php

namespace Curso\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * zonaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class zonaRepository extends EntityRepository
{
}
